apiVersion: v1
kind: Service
metadata:
  name: financial-agent-service
spec:
  type: LoadBalancer
  selector:
    app: financial-agent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000