FROM python:3.12-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app
COPY . /app

RUN uv add streamlit
# sync --frozen --no-cache

EXPOSE 8501

CMD ["/app/.venv/bin/streamlit", "run", "streamlit_app/ui.py", "--server.port=8501", "--server.address=0.0.0.0"]
